name: Feature Request
description: Sugira uma melhoria para o plugin
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problema relacionado
      description: Esta feature resolve algum problema?
  - type: textarea
    attributes:
      label: Solução desejada
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternativas consideradas
